### ISSUE TITLE
POST https://www.openfood.ch/api/v2/products/_search return 500 Error

### ISSUE THREAD

**Issue by ChernyshenkoTaras** [salathegroup/openfood_api#12]
API call POST https://www.openfood.ch/api/v2/products/_search
params: 
{
"query" : "<any_param>"
}
return response:
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

**Comment by scarroll32** [comment]
Hi @ChernyshenkoTaras, thanks for logging this. We cannot replicate this error ourselves: could you please send us the query itself as well as how you are calling it. You can post it here or email us at contact@openfood.ch if you prefer.

**Comment by ChernyshenkoTaras** [comment]
@seanfcarroll 
POST https://www.openfood.ch/api/v2/products/_search?query=milk
Authorization: Token token=\<REDACTED>
Cookie: _open_food_api_session=\<REDACTED>
Host: www.openfood.ch
Connection: close
User-Agent: Paw/3.0.16 (Macintosh; OS X/10.12.1) GCDHTTPRequest
Content-Length: 0

**Comment by bkDJ** [comment]
@ChernyshenkoTaras The issues in what you provided are `?query=milk` and`Content-Length: 0`. The /products/_search API endpoint doesn't take any parameters in the URL; instead there should be a query using the [ElasticSearch Query DSL in JSON](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) in the body of the POST. An example query for finding all products with 'milk' in their english ingredients would be:
```json
{
  "query": {
    "term": {
      "ingredients_translations.en" : "milk"
    }
  }
}
```

On OpenFood's end, it was incorrect to return a 500 in the case of a malformed or empty query. As of now, doing so should result in a 400 error.

Please note: We do have plans on a V3 API for next month, with cleaner responses and better documentation.
