### ISSUE TITLE
OpenFood-api v2 throws CORS error

### ISSUE THREAD

**Issue by PhilippRoessner** [salathegroup/openfood_api#15]
today I encounter problems with accessing the API. 

> Failed to load https://www.openfood.ch/api/v2/products/_search: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

**Comment by PhilippRoessner** [comment]
Seems to work after changing all URLs from openfood.ch to foodrepo.org

**Comment by bkDJ** [comment]
Also please consider using v3. The search endpoint is more flexible, and v2 may be sunset soon.

**Comment by bkDJ** [comment]
CORS headers added back to old endpoints.
