### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by Boris-c** [salathegroup/openfood_api#17]
Pagination on product API calls doesn't work any more. Neither page number nor number of items per page. First page with 20 items is always returned.

**Comment by Hentzware** [comment]
For me it stops at page 150 of 210 with a page size of 200 and Accept-Encoding Gzip. I get a bad request message from the server.

**Comment by balakirevs** [comment]
@Boris-c, @DoKOne is it ok now?

**Comment by Hentzware** [comment]
It works now.
